#pragma once

#include <string>
using std::string;

string conversion(char curr) {
	switch (curr) {
	case '1': return "C2";
	case '!': return "C#2";
	case '2': return "D2";
	case '@': return "D#2";
	case '3': return "E2";
	case '4': return "F2";
	case '$': return "F#2";
	case '5': return "G2";
	case '%': return "G#2";
	case '6': return "A2";
	case '^': return "A#2";
	case '7': return "B2";
	case '8': return "C3";
	case '*': return "C#3";
	case '9': return "D3";
	case '(': return "D#3";
	case '0': return "E3";
	case 'q': return "F3";
	case 'Q': return "F#3";
	case 'w': return "G3";
	case 'W': return "G#3";
	case 'e': return "A3";
	case 'E': return "A#3";
	case 'r': return "B3";
	case 't': return "C4";
	case 'T': return "C#4";
	case 'y': return "D4";
	case 'Y': return "D#4";
	case 'u': return "E4";
	case 'i': return "F4";
	case 'I': return "F#4";
	case 'o': return "G4";
	case 'O': return "G#4";
	case 'p': return "A4";
	case 'P': return "A#4";
	case 'a': return "B4";
	case 's': return "C5";
	case 'S': return "C#5";
	case 'd': return "D5";
	case 'D': return "D#5";
	case 'f': return "E5";
	case 'g': return "F5";
	case 'G': return "F#5";
	case 'h': return "G5";
	case 'H': return "G#5";
	case 'j': return "A5";
	case 'J': return "A#5";
	case 'k': return "B5";
	case 'l': return "C6";
	case 'L': return "C#6";
	case 'z': return "D6";
	case 'Z': return "D#6";
	case 'x': return "E6";
	case 'c': return "F6";
	case 'C': return "F#6";
	case 'v': return "G6";
	case 'V': return "G#6";
	case 'b': return "A6";
	case 'B': return "A#6";
	case 'n': return "B6";
	case ' ': return "_";
	case '|': return "__";
	case '[': return "[";
	case ']': return "]";
	}
}

char reverseConversion(string curr) {
	if (curr == "C2") return '1';
	if (curr == "C#2") return '!';
	if (curr == "D2") return '2';
	if (curr == "D#2") return '@';
	if (curr == "E2") return '3';
	if (curr == "F2") return '4';
	if (curr == "F#2") return '$';
	if (curr == "G2") return '5';
	if (curr == "G#2") return '%';
	if (curr == "A2") return '6';
	if (curr == "A#2") return '^';
	if (curr == "B2") return '7';
	if (curr == "C3") return '8';
	if (curr == "C#3") return '*';
	if (curr == "D3") return '9';
	if (curr == "D#3") return '(';
	if (curr == "E3") return '0';
	if (curr == "F3") return 'q';
	if (curr == "F#3") return 'Q';
	if (curr == "G3") return 'w';
	if (curr == "G#3") return 'W';
	if (curr == "A3") return 'e';
	if (curr == "A#3") return 'E';
	if (curr == "B3") return 'r';
	if (curr == "C4") return 't';
	if (curr == "C#4") return 'T';
	if (curr == "D4") return 'y';
	if (curr == "D#4") return 'Y';
	if (curr == "E4") return 'u';
	if (curr == "F4") return 'i';
	if (curr == "F#4") return 'I';
	if (curr == "G4") return 'o';
	if (curr == "G#4") return 'O';
	if (curr == "A4") return 'p';
	if (curr == "A#4") return 'P';
	if (curr == "B4") return 'a';
	if (curr == "C5") return 's';
	if (curr == "C#5") return 'S';
	if (curr == "D5") return 'd';
	if (curr == "D#5") return 'D';
	if (curr == "E5") return 'f';
	if (curr == "F5") return 'g';
	if (curr == "F#5") return 'G';
	if (curr == "G5") return 'h';
	if (curr == "G#5") return 'H';
	if (curr == "A5") return 'j';
	if (curr == "A#5") return 'J';
	if (curr == "B5") return 'k';
	if (curr == "C6") return 'l';
	if (curr == "C#6") return 'L';
	if (curr == "D6") return 'z';
	if (curr == "D#6") return 'Z';
	if (curr == "E6") return 'x';
	if (curr == "F6") return 'c';
	if (curr == "F#6") return 'C';
	if (curr == "G6") return 'v';
	if (curr == "G#6") return 'V';
	if (curr == "A6") return 'b';
	if (curr == "A#6") return 'B';
	if (curr == "B6") return 'n';
	if (curr == "_") return ' ';
	if (curr == "__") return '|';
	if (curr == "[") return '[';
	if (curr == "]") return ']';
	return ' ';
}
